name: 'FAIRly Obsessed: A MN State Fair Love Affair'
description: 'A personal blog about our family adventures at the Minnesota State Fair.'
email: fran@fabriziofamily.com
baseurl: ""
disqus: fairly-obsessed
favicon: assets/images/favicon.ico

include: ["_pages"]
permalink: /:title/

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

remote_theme: franfabrizio/mundana-theme-jekyll

feed:
  disable_in_development: true

authors:
    fran:
      name:           Fran
      avatar:         assets/images/avatar1.jpg
      bio:            "My happy place is wherever I am while holding a Mini Donut Beer."
      email:          fran@fabriziofamily.com
      facebook:       https://www.facebook.com/fran.fabrizio
      twitter:        https://twitter.com/FAIRlyobsessmn

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: fran
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

paginate: 10